### ISSUE TITLE
Driver file does not exist.

### ISSUE THREAD

**Issue by hatemnsec** [ReversecLabs/physmem2profit#1]
I got a weird issue, on client 

`[root:...ysmem/physmem2profit/client]# python3 physmem2profit --mode all --host 192.168.17.162 --port 8081 --driver winpmem --install C:\Users\att_winpmem_64.sys --label dg-gdsf                             (public✱) 
[*] Connecting to 192.168.17.162 on port 8081
[*] Connected
[*] Loading config from config.json
Process Process-1:
Traceback (most recent call last):
  File "/usr/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/usr/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "physmem2profit/__main__.py", line 57, in <lambda>
    jobs.append(Process(target=lambda: mount.mount(socket, args.driver, args.install)))     # mount will block thread, it need to be handled by child process.
  File "physmem2profit/mount.py", line 351, in mount
    fuse = FUSE(Physmem(sock, mountpoint, driver, installArguments), mountpoint, nothreads=True, foreground=True)
  File "physmem2profit/mount.py", line 46, in __init__
    raise Exception(struct.unpack("<%ds" % response, self.socket.recv(response))[0].decode('utf-8'))
Exception: Driver file does not exist.
[*] Read 0 MB, cached reads 0 MB
Process Process-2:
Traceback (most recent call last):
  File "/usr/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/usr/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "physmem2profit/__main__.py", line 59, in <lambda>
    jobs.append(Process(target=lambda: physmem2minidump.dump(args.label)))
  File "physmem2profit/physmem2minidump.py", line 144, in dump
    ensureFileExist(CONFIG_FILE)
  File "physmem2profit/physmem2minidump.py", line 134, in ensureFileExist
    raise Exception('File does not exist: ' + path)
Exception: File does not exist: config.json
[root:...ysmem/physmem2profit/client]#              `

Then on server, 

`[*] Registering driver bridges.
[+] Found driver bridge: WinPmem.
[+]    Registered command: Install.
[+]    Registered command: Uninstall.
[+]    Registered command: Map.
[+]    Registered command: Read.
[*] Starting server on 192.168.17.162:8081...
[+] Server Started.
[*] Waiting for a connection...
[+] Connected!
[*] Installing service...
[*] Creating service physmem2profit...
[-] Driver file does not exist.
                                     `

though I downloaded the driver and place it in the same folder.

**Comment by hatemnsec** [comment]
it was a silly issue in single quotes --install 'C:\Users\att_winpmem_64.sys'

**Comment by iinviisiible** [comment]
Hello @hatemnsec, have you managed to solve the "config.json" issue?
I'm experiencing the same issue
